In [2]:
# Импортируем наши библиотеки    
from bs4 import BeautifulSoup    
import requests
import urllib.request
from os import system
import json
import ssl
import codecs
import pandas as pd
import numpy as np
import re as re
import time

In [3]:
def parse_tth(tth, descr, rec_id, price):
    global df_all
    d = {}
    
    try:
        try:
            for tag in tth.find_all('li'):
                prm = str(tag.text).split(':')
                d[str(prm[0]).strip()] = [str(prm[1]).strip()]
        except:
            return -1
        
        #Добавление/трансформация колонок
        d['price'] = price
        d['url'] = [tth_url]
        
        try:
            numberOfDoors = float(d['Количество дверей'][0])
        except:
            numberOfDoors = 4.0
        d['numberOfDoors'] = numberOfDoors
        
        try:
            d['bodyType'] = d['Тип кузова']
            if d['Тип кузова'][0] in ['внедорожник', 'хетчбэк', 'универсал', 'седан']:
                d['bodyType'] = [d['bodyType'][0]+' '+str(numberOfDoors)+' дв.']
        except:
            d['bodyType'] = None
    
        try:
            modelDate = float(re.search('\d{4}', d['Поколение'][0])[0])
        except:
            modelDate = None
        d['modelDate'] = modelDate
        
        try:
            productionDate = float(d['Год выпуска'])
        except:
            productionDate = modelDate
        d['productionDate'] = productionDate

        try:
            volume = re.search('\d\.\d', d['Модификация'][0])[0]
            d['vehicleConfiguration'] = d['Тип кузова'][0]+' '+d['Коробка передач'][0]+' '+volume
        except:
            volume = 0
            d['vehicleConfiguration'] = None

        try:
            if d['Коробка передач'][0] == 'автомат':
                d['vehicleTransmission'] = 'автоматическая'
            elif d['Коробка передач'][0] == 'механика':
                d['vehicleTransmission'] = 'механическая'
            elif d['Коробка передач'][0] == 'робот':
                d['vehicleTransmission'] = 'роботизированная'
            else:
                d['vehicleTransmission'] = 'other'
        except:
            d['vehicleTransmission'] = 'Other'

        if float(volume) > 0:
            d['engineDisplacement'] = str(volume)+' LTR'
        else:
            d['engineDisplacement'] = None

        try:
            power = re.search('\d{2,} ', d['Модификация'][0])[0]
        except:
            power = 0
        if float(volume) > 0:
            d['enginePower'] = str(power)+'N12'
        else:
            d['enginePower'] = None

        d['description'] = descr

        try:
            mileage = float(re.search('\d{0,}', d['Пробег'][0])[0])
        except:
            mileage = 0.0
        d['mileage'] = mileage
        
        try:
            d['Состояние'] = d['Состояние']
        except:
            d['Состояние'] = None
        
        try:
            driver_qnt = re.search('\d{1,}', d['Владельцев по ПТС'][0])[0]
        except:
            driver_qnt = '0'
        if int(driver_qnt) == 0:
            d['Владельцы'] = driver_qnt+' владельцев'
        elif int(driver_qnt) == 1:
            d['Владельцы'] = driver_qnt+' владелец'
        elif int(driver_qnt) == 2:
            d['Владельцы'] = driver_qnt+' владельца'
        elif int(driver_qnt) >= 3:
            d['Владельцы'] = driver_qnt+' или более'
    
        #Пока неоткуда брать данные
        d['ПТС'] = 'Оригинал'       #пример: Оригинал
        d['Таможня'] = 'Растаможен' #пример: Растаможен
        
        #Рассчитаем сред. срок относительно июня 2020г. и считая кол-во владельцев по ПТС
        if driver_qnt == 0:
            d['Владение'] = np.NaN #пример: NaN или "5 лет и 3 месяца"
        else:
            m_add = 6 #кол-во месяцев текущего года
            y_qnt = round(12*(2020.0 - productionDate) // 12 / driver_qnt)
            m_qnt = round((12*(2020.0 - productionDate) + m_add) % 12 / driver_qnt)
           
            y_qnt_str = 'лет'
            m_qnt_str = 'месяцев'
            
            if y_qnt == 1: y_qnt_str = 'год'
            elif 2 <= y_qnt <= 4: y_qnt_str = 'года'
            
            if m_qnt == 1: m_qnt_str = 'месяц'
            elif 2 <= m_qnt <= 4: m_qnt_str = 'месяца'
                
            if y_qnt == 0:
                d['Владение'] = str(m_qnt)+' '+m_qnt_str
            else:
                d['Владение'] = str(y_qnt)+' '+y_qnt_str+' '+str(m_qnt)+' '+m_qnt_str

        #Заполняем сквозной нумерацией
        d['id'] = rec_id

        #Приведение к формату файла test.csv
        df = pd.DataFrame(d)
        df_one = pd.concat(
            [
            df['bodyType'], df['Марка'], df['Цвет'], df['Тип двигателя'], df['modelDate'], 
            df['Модификация'], df['numberOfDoors'], df['productionDate'], df['vehicleConfiguration'],
            df['vehicleTransmission'], df['engineDisplacement'], df['enginePower'], 
            df['description'], df['mileage'], df['Комплектация'], df['Привод'], df['Руль'], 
            df['Состояние'], df['Владельцы'], df['ПТС'], df['Таможня'], df['Владение'],
            df['id'], df['price'], df['url']
            ],
            axis=1
        )
        df_one.columns=[
            'bodyType', 'brand', 'color', 'fuelType', 'modelDate', 
            'name', 'numberOfDoors', 'productionDate', 'vehicleConfiguration', 
            'vehicleTransmission', 'engineDisplacement', 'enginePower', 
            'description', 'mileage', 'Комплектация', 'Привод', 'Руль', 
            'Состояние', 'Владельцы', 'ПТС', 'Таможня', 'Владение',
            'id', 'price', 'url'
        ]

        df_all = df_all.append(df_one, ignore_index=True)
    except (KeyError, TypeError) as err:
        df_all.to_csv('avito_tmp_'+time.strftime('%Y%m%d%H%M%S', time.localtime())+'.csv')
        print(tth_url, ':', type(err), ': {}'.format(err.args[-1]))
    
    return 0

In [17]:
# Проверка функции
# df_all = pd.DataFrame()
print(parse_tth(tth, descr, 1, 1e6))
# df_all.to_csv('tmp.csv')
df_all

0

,bodyType,brand,color,fuelType,modelDate,name,numberOfDoors,productionDate,vehicleConfiguration,vehicleTransmission,...,Привод,Руль,Состояние,Владельцы,ПТС,Таможня,Владение,id,price,url
0,внедорожник 5.0 дв.,Renault,белый,бензин,2016.0,2.0 4WD MT (143 л.с.),5.0,2016.0,внедорожник механика 2.0,механическая,...,полный,левый,None,0,Оригинал,Растаможен,NaN,0,1029000.0,https://www.avito.ru/moskva/avtomobili/renault...
1,седан 4.0 дв.,KIA,жёлтый,бензин,2015.0,1.6 MT (123 л.с.),4.0,2015.0,седан механика 1.6,механическая,...,передний,левый,не битый,3,Оригинал,Растаможен,2 года 2 месяца,1,398000.0,https://www.avito.ru/moskva/avtomobili/kia_rio...
2,хетчбэк 5.0 дв.,Skoda,серый,бензин,2008.0,1.4 TSI DSG (122 л.с.),5.0,2008.0,хетчбэк робот 1.4,роботизированная,...,передний,левый,не битый,2,Оригинал,Растаможен,6 лет 3 месяца,2,459000.0,https://www.avito.ru/moskva/avtomobili/skoda_o...
3,седан 4.0 дв.,Mercedes-Benz,чёрный,бензин,2013.0,S 500 4.7 4MATIC 7G-Tronic (455 л.с.),4.0,2013.0,седан автомат 4.7,автоматическая,...,полный,левый,не битый,1,Оригинал,Растаможен,7 лет 6 месяцев,3,2175000.0,https://www.avito.ru/moskva/avtomobili/mercede...
4,внедорожник 5.0 дв.,Suzuki,оранжевый,бензин,2009.0,1.6 4WD AT (112 л.с.),5.0,2009.0,внедорожник автомат 1.6,автоматическая,...,полный,левый,не битый,2,Оригинал,Растаможен,6 лет 3 месяца,4,510000.0,https://www.avito.ru/moskva/avtomobili/suzuki_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,микроавтобус,Mercedes-Benz,белый,дизель,2006.0,515 CDI 2.2 MT (150 л.с.),4.0,2006.0,микроавтобус механика 2.2,механическая,...,задний,левый,не битый,2,Оригинал,Растаможен,7 лет 3 месяца,387,1800000.0,https://www.avito.ru/moskva/avtomobili/mercede...
388,внедорожник 5.0 дв.,Mitsubishi,чёрный,бензин,2006.0,3.0 4WD AT (178 л.с.),5.0,2006.0,внедорожник автомат 3.0,автоматическая,...,полный,левый,не битый,1,Оригинал,Растаможен,14 лет 6 месяцев,388,799000.0,https://www.avito.ru/moskva/avtomobili/mitsubi...
389,седан 4.0 дв.,Toyota,синий,бензин,2001.0,2.4 AT (159 л.с.),4.0,2001.0,седан автомат 2.4,автоматическая,...,передний,левый,не битый,1,Оригинал,Растаможен,19 лет 6 месяцев,389,447000.0,https://www.avito.ru/moskva/avtomobili/toyota_...
390,седан 4.0 дв.,Ford,чёрный,бензин,2010.0,2.3 AT (161 л.с.),4.0,2010.0,седан автомат 2.3,автоматическая,...,передний,левый,не битый,2,Оригинал,Растаможен,5 лет 3 месяца,390,535000.0,https://www.avito.ru/moskva/avtomobili/ford_mo...
391,хетчбэк 5.0 дв.,Tesla,коричневый,электро,2012.0,85,5.0,2012.0,None,автоматическая,...,задний,левый,не битый,2,Оригинал,Растаможен,4 года 3 месяца,1,1000000.0,https://www.avito.ru/moskva/avtomobili/tesla_m...

In [4]:
def process_tth_url(tth_url, only_descr=False):
    if tth_url.find('automama') > 0: #ссылки на другой сайт игнорируем
        if only_descr:
            return -1
        else:
            return [-1,-1,-1]

    try: #Переходим на страницу с ТТХ
        tth_response = requests.get(tth_url, headers={'User-Agent': 'Mozilla/5.0'})    
        tth_page = BeautifulSoup(tth_response.text, 'html.parser')    
    except:
        if only_descr:
            return -1
        else:
            return [-1,-1,-1]

    try: #Описание про автомобиль лежит отдельно
        descr = tth_page.find('div', class_='item-description-text').text.strip()
    except:
        try:
            descr = tth_page.find('div', class_='item-description-html').text.strip()
        except:
            descr = None

    if only_descr:
        return descr
    else:
        tth = tth_page.find('ul', class_='item-params-list')

        try:
            #Цена также в отдельном месте
            price = tth_page.find('span', class_='js-item-price')
            price = float(price.attrs['content'])
        except AttributeError:
            price = 0

        return [tth, descr, price]

# process_tth_url('https://www.avito.ru/moskva/avtomobili/volkswagen_tiguan_2012_1867991470', 
#                 only_descr=True)

In [3]:
url_city = {
    'Москва':'https://www.avito.ru/moskva/avtomobili?s=104&radius=0&p=',
    #'МосО':'https://www.avito.ru/moskovskaya_oblast/avtomobili?s=104&p=',
    #'Питер':'https://www.avito.ru/sankt-peterburg/avtomobili?s=104&radius=0&p=',
    #'ЛенО':'https://www.avito.ru/leningradskaya_oblast/avtomobili?s=104&p=',
    #'СверО':'https://www.avito.ru/sverdlovskaya_oblast/avtomobili?s=104&p=',
    #'РостО':'https://www.avito.ru/rostovskaya_oblast/avtomobili?s=104&p=',
    #'ЧелО':'https://www.avito.ru/chelyabinskaya_oblast/avtomobili?s=104&p=',
    #'КраснодК':'https://www.avito.ru/krasnodarskiy_kray/avtomobili?s=104&p=',
    #'СамО':'https://www.avito.ru/samarskaya_oblast/avtomobili?s=104&p='
} #осн. адрес, к нему будем добавлять номер страницы

In [4]:
cnt_ads = 39623  #счетчик объявлений
cnt_err = 0  #счетчик ошибок
df_all = pd.DataFrame()

qnt4compare = 1000
is_debug = False

print(time.strftime('%d.%m.%Y %H:%M:%S', time.localtime())+\
      ': Парсинг автомобильных объявлений с сайта avito.ru ...')
if is_debug:
    print('!Отладка включена!')

for key in url_city.keys():
    if is_debug:
        if cnt_ads > qnt4compare:
            print('Прерываем цикл. cnt_ads =',cnt_ads)
            df_all.to_csv('avito_auto_'+str(cnt_ads)+'.csv')
            break
    print('     ===== Регион ['+key+'] =====')
    
    for cnt_page in range(1,101): #на сайте отображены только 100 страниц
        if is_debug:
            if cnt_ads > qnt4compare:
                break

        url = url_city[key]+str(cnt_page)
        try:
            response = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})    
            page = BeautifulSoup(response.text, 'html.parser')
        except:
            print('Ошибка выполнения!')
            break

        #Получаем список объявлений на странице
        ads = page.find('div', class_='snippet-list js-catalog_serp')
        
        try:
            for ad in ads.find_all('a', class_='snippet-link'):
                if is_debug:
                    if cnt_ads > qnt4compare:
                        break

                tth_url = 'https://www.avito.ru'+ad.attrs['href']
                lst_prm = process_tth_url(tth_url)
                if lst_prm[0] != -1:
                    tth, descr, price = lst_prm[0], lst_prm[1], lst_prm[2]
                    #Парсинг данных
                    if parse_tth(tth=tth, descr=descr, rec_id=cnt_ads+1, price=price) == 0:
                        cnt_ads += 1
                        if cnt_ads % (qnt4compare/10) == 0:
                            print(time.strftime('%d.%m.%Y %H:%M:%S', time.localtime())+': Обработано', 
                                  cnt_ads, 'объявлений')
                        if cnt_ads % qnt4compare == 0:
                            df_all.to_csv('avito_auto_'+str(cnt_ads)+'_'+key+'.csv')
                            df_all = pd.DataFrame()

                time.sleep(1) #на всякий случай задержка
        except:
            continue
    #end for cnt_page
    
# Дописываем последние записи
if cnt_ads % qnt4compare != 0:
    df_all.to_csv('avito_auto_'+str(cnt_ads)+'.csv')
print('Всего обработано', cnt_ads, 'объявлений')

21.06.2020 10:20:25: Парсинг автомобильных объявлений с сайта avito.ru ...
     ===== Регион [Москва] =====
21.06.2020 10:23:43: Обработано 39700 объявлений
21.06.2020 10:27:48: Обработано 39800 объявлений
21.06.2020 10:31:41: Обработано 39900 объявлений
21.06.2020 10:35:16: Обработано 40000 объявлений
21.06.2020 10:39:25: Обработано 40100 объявлений
https://www.avito.ru/moskva/avtomobili/opel_astra_2013_1903079068 : <class 'TypeError'> : unsupported operand type(s) for -: 'float' and 'NoneType'
21.06.2020 10:43:24: Обработано 40200 объявлений
21.06.2020 10:47:18: Обработано 40300 объявлений
21.06.2020 10:50:48: Обработано 40400 объявлений
21.06.2020 10:54:45: Обработано 40500 объявлений
21.06.2020 10:59:06: Обработано 40600 объявлений
21.06.2020 11:02:03: Обработано 40700 объявлений
21.06.2020 11:04:44: Обработано 40800 объявлений
21.06.2020 11:07:48: Обработано 40900 объявлений
21.06.2020 11:11:15: Обработано 41000 объявлений
21.06.2020 11:15:51: Обработано 41100 объявлений
21.06.2020 11:21:34: Обработано 41200 объявлений
21.06.2020 11:26:02: Обработано 41300 объявлений
21.06.2020 11:29:41: Обработано 41400 объявлений
21.06.2020 11:32:43: Обработано 41500 объявлений
21.06.2020 11:36:29: Обработано 41600 объявлений
21.06.2020 11:40:48: Обработано 41700 объявлений
21.06.2020 11:44:01: Обработано 41800 объявлений
21.06.2020 11:47:30: Обработано 41900 объявлений
21.06.2020 11:51:45: Обработано 42000 объявлений
21.06.2020 11:56:10: Обработано 42100 объявлений
21.06.2020 12:00:01: Обработано 42200 объявлений
21.06.2020 12:04:04: Обработано 42300 объявлений
21.06.2020 12:07:41: Обработано 42400 объявлений
21.06.2020 12:12:03: Обработано 42500 объявлений
21.06.2020 12:15:59: Обработано 42600 объявлений
21.06.2020 12:20:35: Обработано 42700 объявлений
21.06.2020 12:24:44: Обработано 42800 объявлений
21.06.2020 12:28:47: Обработано 42900 объявлений
21.06.2020 12:32:56: Обработано 43000 объявлений
21.06.2020 12:37:29: Обработано 43100 объявлений
https://www.avito.ru/moskva/avtomobili/kia_cerato_2010_1903464782 : <class 'TypeError'> : unsupported operand type(s) for -: 'float' and 'NoneType'
https://www.avito.ru/moskva/avtomobili/opel_astra_2010_1903685402 : <class 'TypeError'> : unsupported operand type(s) for -: 'float' and 'NoneType'
https://www.avito.ru/moskva/avtomobili/kia_cerato_2010_1903464782 : <class 'TypeError'> : unsupported operand type(s) for -: 'float' and 'NoneType'
https://www.avito.ru/moskva/avtomobili/opel_astra_2010_1903685402 : <class 'TypeError'> : unsupported operand type(s) for -: 'float' and 'NoneType'
21.06.2020 12:42:39: Обработано 43200 объявлений
21.06.2020 12:47:02: Обработано 43300 объявлений
21.06.2020 12:51:24: Обработано 43400 объявлений
21.06.2020 12:55:56: Обработано 43500 объявлений
21.06.2020 13:00:48: Обработано 43600 объявлений
21.06.2020 13:05:13: Обработано 43700 объявлений
21.06.2020 13:09:16: Обработано 43800 объявлений
21.06.2020 13:13:21: Обработано 43900 объявлений
21.06.2020 13:17:48: Обработано 44000 объявлений
21.06.2020 13:22:00: Обработано 44100 объявлений
21.06.2020 13:26:03: Обработано 44200 объявлений
21.06.2020 13:31:00: Обработано 44300 объявлений
21.06.2020 13:35:54: Обработано 44400 объявлений
21.06.2020 13:40:59: Обработано 44500 объявлений
21.06.2020 13:45:16: Обработано 44600 объявлений
21.06.2020 13:49:47: Обработано 44700 объявлений
21.06.2020 13:54:09: Обработано 44800 объявлений
21.06.2020 13:58:29: Обработано 44900 объявлений
21.06.2020 14:02:56: Обработано 45000 объявлений
21.06.2020 14:06:51: Обработано 45100 объявлений
21.06.2020 14:11:09: Обработано 45200 объявлений
https://www.avito.ru/moskva/avtomobili/hyundai_solaris_2015_1933069157 : <class 'TypeError'> : unsupported operand type(s) for -: 'float' and 'NoneType'
21.06.2020 14:14:49: Обработано 45300 объявлений
21.06.2020 14:18:45: Обработано 45400 объявлений
https://www.avito.ru/moskva/avtomobili/toyota_corolla_2013_1924631533 : <class 'TypeError'> : unsupported operand type(s) for -: 'float' and 'NoneType'
21.06.2020 14:22:18: Обработано 45500 объявлений
Всего обработано 45581 объявлений

In [46]:
# Формат файла, к которому нужно привести распарсенные данные
# test_short = pd.read_csv('data/test_short.csv', sep=';')
# test_short.head(1).T

In [10]:
# df_all.columns

Index(['bodyType', 'brand', 'color', 'fuelType', 'modelDate', 'name',
       'numberOfDoors', 'productionDate', 'vehicleConfiguration',
       'vehicleTransmission', 'engineDisplacement', 'enginePower',
       'description', 'mileage', 'Комплектация', 'Привод', 'Руль', 'Состояние',
       'Владельцы', 'ПТС', 'Таможня', 'Владение', 'id', 'price', 'url'],
      dtype='object')

In [5]:
df_test = pd.read_csv('data/test.csv')
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3837 entries, 0 to 3836
Data columns (total 23 columns):
bodyType                3837 non-null object
brand                   3837 non-null object
color                   3837 non-null object
fuelType                3837 non-null object
modelDate               3837 non-null float64
name                    3837 non-null object
numberOfDoors           3837 non-null float64
productionDate          3837 non-null float64
vehicleConfiguration    3837 non-null object
vehicleTransmission     3837 non-null object
engineDisplacement      3837 non-null object
enginePower             3837 non-null object
description             3837 non-null object
mileage                 3837 non-null float64
Комплектация            3837 non-null object
Привод                  3837 non-null object
Руль                    3837 non-null object
Состояние               3837 non-null object
Владельцы               3837 non-null object
ПТС                     3837 non-null object
Таможня                 3837 non-null object
Владение                1753 non-null object
id                      3837 non-null int64
dtypes: float64(4), int64(1), object(18)
memory usage: 689.6+ KB

In [87]:
col = 'Владение'
print(df_test[col].unique())
df_train[col].unique()

[nan '7 лет и 2 месяца' '2 года и 11 месяцев' '7 лет' '8 месяцев'
 '7 лет и 3 месяца' '1 год и 1 месяц' '6 месяцев' '2 года и 3 месяца'
 '3 года и 8 месяцев' '1 год и 7 месяцев' '5 лет и 9 месяцев'
 '1 год и 5 месяцев' '1 год и 9 месяцев' '2 года и 5 месяцев'
 '6 лет и 5 месяцев' '5 лет и 7 месяцев' '1 год и 10 месяцев' '9 лет'
 '3 года и 4 месяца' '4 года' '7 лет и 4 месяца' '4 года и 4 месяца'
 '2 года и 1 месяц' '3 года и 11 месяцев' '9 месяцев' '10 лет и 6 месяцев'
 '7 лет и 8 месяцев' '3 года и 5 месяцев' '1 год и 6 месяцев' '5 лет'
 '7 лет и 1 месяц' '2 года и 4 месяца' '1 год и 2 месяца'
 '12 лет и 1 месяц' '1 год' '1 месяц' '10 лет и 4 месяца'
 '4 года и 5 месяцев' '3 года и 9 месяцев' '7 месяцев' '3 года и 1 месяц'
 '6 лет и 6 месяцев' '3 года и 10 месяцев' '2 года и 10 месяцев'
 '6 лет и 9 месяцев' '5 лет и 4 месяца' '10 месяцев' '11 лет и 2 месяца'
 '1 год и 4 месяца' '2 года и 8 месяцев' '2 года и 9 месяцев'
 '1 год и 3 месяца' '1 год и 8 месяцев' '5 месяцев' '3 года и 3 месяца'
 '2 года и 7 месяцев' '5 лет и 8 месяцев' '4 года и 3 месяца' '11 месяцев'
 '4 года и 11 месяцев' '3 года и 2 месяца' '2 года' '5 лет и 1 месяц'
 '8 лет и 1 месяц' '1 год и 11 месяцев' '6 лет и 4 месяца'
 '4 года и 6 месяцев' '9 лет и 2 месяца' '4 года и 8 месяцев'
 '4 года и 9 месяцев' '12 лет и 10 месяцев' '3 месяца'
 '2 года и 6 месяцев' '5 лет и 5 месяцев' '11 лет и 8 месяцев'
 '4 года и 2 месяца' '3 года и 6 месяцев' '6 лет' '6 лет и 11 месяцев'
 '4 месяца' '7 лет и 6 месяцев' '4 года и 10 месяцев' '8 лет и 8 месяцев'
 '12 лет и 2 месяца' '2 месяца' '6 лет и 2 месяца' '4 года и 7 месяцев'
 '8 лет и 2 месяца' '2 года и 2 месяца' '4 года и 1 месяц' '3 года'
 '5 лет и 10 месяцев' '8 лет' '6 лет и 3 месяца' '9 лет и 6 месяцев'
 '7 лет и 5 месяцев' '10 лет и 11 месяцев' '5 лет и 6 месяцев'
 '6 лет и 8 месяцев' '3 года и 7 месяцев' '8 лет и 11 месяцев'
 '13 лет и 2 месяца' '11 лет и 6 месяцев' '6 лет и 10 месяцев'
 '14 лет и 4 месяца' '5 лет и 2 месяца' '8 лет и 3 месяца'
 '12 лет и 11 месяцев' '16 лет и 8 месяцев' '9 лет и 11 месяцев'
 '9 лет и 5 месяцев' '6 лет и 7 месяцев' '6 лет и 1 месяц'
 '7 лет и 10 месяцев' '12 лет и 5 месяцев' '7 лет и 9 месяцев'
 '8 лет и 7 месяцев' '5 лет и 11 месяцев' '5 лет и 3 месяца'
 '11 лет и 3 месяца' '15 лет и 10 месяцев' '9 лет и 3 месяца'
 '16 лет и 9 месяцев' '18 лет и 5 месяцев' '8 лет и 10 месяцев'
 '14 лет и 6 месяцев' '10 лет и 3 месяца' '27 лет и 3 месяца'
 '9 лет и 1 месяц' '9 лет и 9 месяцев' '11 лет и 4 месяца'
 '10 лет и 2 месяца' '7 лет и 11 месяцев' '9 лет и 7 месяцев'
 '10 лет и 10 месяцев' '15 лет и 5 месяцев' '9 лет и 4 месяца'
 '9 лет и 10 месяцев' '11 лет и 1 месяц' '8 лет и 4 месяца'
 '8 лет и 5 месяцев' '10 лет и 1 месяц' '14 лет и 7 месяцев'
 '10 лет и 9 месяцев' '8 лет и 9 месяцев' '10 лет и 8 месяцев'
 '15 лет и 9 месяцев' '8 лет и 6 месяцев' '15 лет и 8 месяцев'
 '12 лет и 7 месяцев' '16 лет и 6 месяцев' '7 лет и 7 месяцев' '11 лет'
 '13 лет и 1 месяц' '10 лет' '16 лет и 2 месяца' '9 лет и 8 месяцев']

array(['6 лет 3 месяца', '5 лет 2 месяца', '3 года 2 месяца',
       '4 года 2 месяца', '8 лет 3 месяца', '9 лет 3 месяца',
       '5 лет 6 месяцев', '10 лет 6 месяцев', '26 лет 3 месяца',
       '12 лет 2 месяца', '24 лет 6 месяцев', '2 года 2 месяца',
       '7 лет 2 месяца', '8 лет 2 месяца', '4 года 3 месяца',
       '9 лет 6 месяцев', '15 лет 6 месяцев', '11 лет 6 месяцев',
       '2 года 6 месяцев', '6 лет 6 месяцев', '7 лет 6 месяцев',
       '12 лет 6 месяцев', '3 года 6 месяцев', '1 год 6 месяцев',
       '2 года 3 месяца', '22 лет 3 месяца', '7 лет 3 месяца',
       '3 года 3 месяца', '41 лет 6 месяцев', '5 лет 3 месяца',
       '6 лет 2 месяца', '1 год 2 месяца', '10 лет 2 месяца',
       '11 лет 2 месяца', '13 лет 6 месяцев', '8 лет 6 месяцев',
       '14 лет 6 месяцев', '1 год 3 месяца', '16 лет 3 месяца',
       '12 лет 3 месяца', '10 лет 3 месяца', '53 лет 6 месяцев',
       '23 лет 6 месяцев', '19 лет 3 месяца', '20 лет 3 месяца',
       '18 лет 3 месяца', '43 лет 6 месяцев', '4 года 6 месяцев',
       '15 лет 3 месяца', '16 лет 6 месяцев', '9 лет 2 месяца',
       '64 лет 6 месяцев', '17 лет 6 месяцев', '25 лет 6 месяцев',
       '17 лет 2 месяца', '17 лет 3 месяца', '20 лет 6 месяцев',
       '32 лет 6 месяцев', '16 лет 2 месяца', '15 лет 2 месяца',
       '52 лет 6 месяцев', '38 лет 6 месяцев', '13 лет 3 месяца',
       '14 лет 2 месяца', '21 лет 6 месяцев', '24 лет 3 месяца',
       '29 лет 6 месяцев', '14 лет 3 месяца', '13 лет 2 месяца',
       '36 лет 6 месяцев', '18 лет 6 месяцев', '19 лет 2 месяца',
       '32 лет 3 месяца', '33 лет 6 месяцев', '50 лет 6 месяцев',
       '27 лет 6 месяцев', '22 лет 6 месяцев', '28 лет 6 месяцев',
       '61 лет 6 месяцев', '19 лет 6 месяцев', '18 лет 2 месяца',
       '27 лет 3 месяца', '11 лет 3 месяца', '25 лет 3 месяца',
       '6 месяцев', '28 лет 3 месяца', '21 лет 2 месяца',
       '48 лет 6 месяцев', '3 месяца', '55 лет 6 месяцев',
       '30 лет 6 месяцев', '44 лет 6 месяцев', '26 лет 6 месяцев',
       '37 лет 3 месяца', '60 лет 6 месяцев', '40 лет 3 месяца',
       '47 лет 6 месяцев', '84 лет 6 месяцев', '35 лет 6 месяцев',
       '2 месяца', '54 лет 6 месяцев', '45 лет 6 месяцев',
       '31 лет 3 месяца', '20 лет 2 месяца', '22 лет 2 месяца',
       '40 лет 6 месяцев', '66 лет 6 месяцев', '83 лет 6 месяцев',
       '33 лет 3 месяца', '30 лет 3 месяца', '34 лет 3 месяца',
       '67 лет 6 месяцев', '62 лет 6 месяцев', '31 лет 6 месяцев',
       '39 лет 6 месяцев', '46 лет 6 месяцев', '37 лет 6 месяцев',
       '34 лет 6 месяцев', '56 лет 6 месяцев', '21 лет 3 месяца',
       '49 лет 6 месяцев', '58 лет 6 месяцев', '29 лет 2 месяца',
       '74 лет 6 месяцев', '42 лет 6 месяцев', '72 лет 6 месяцев'],
      dtype=object)

In [108]:
# df_train.apply(np.dtype(pd.Series) ) == 'object'
# np.dtype('object')
df_train[df_train.dtype == 'obj']

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [90]:
# col = 'Владение'
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('-390 лет 6 месяцев', 'Нет данных'))
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('-98 лет 2 месяца', 'Нет данных'))
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('-195 лет 3 месяца', 'Нет данных'))
# df_train[col] = df_train[col].apply(lambda x: 'Нет данных' if pd.isna(x) else x)
# df_train.iloc[36145]

bodyType                                                внедорожник 5 дв.
brand                                                          Mitsubishi
color                                                               белый
fuelType                                                           дизель
modelDate                                                            2011
name                                           3.2 DI-D 4WD AT (200 л.с.)
numberOfDoors                                                           5
productionDate                                                       2011
vehicleConfiguration                                ALLROAD AUTOMATIC 3.2
vehicleTransmission                                        автоматическая
engineDisplacement                                                3.2 LTR
enginePower                                                       200 N12
description             Автомобиль в идеальном состоянии. Без сколов и...
mileage                                                            189000
Комплектация                                                     Ultimate
Привод                                                             полный
Руль                                                                Левый
Состояние                                              Не требует ремонта
Владельцы                                                     3 или более
ПТС                                                              Оригинал
Таможня                                                        Растаможен
Владение                                                  2 года 2 месяца
id                                                                  38513
price                                                           1.299e+06
url                     https://www.avito.ru/samara/avtomobili/mitsubi...
Name: 36153, dtype: object

In [64]:
# col = 'Владельцы'
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('1 владелец', '1'+u'\xa0'+'владелец'))
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('2 владельца', '2'+u'\xa0'+'владельца'))

In [58]:
# col = 'Состояние'
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('не битый', 'Не требует ремонта'))

In [54]:
# col = 'Руль'
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('левый', 'Левый'))
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('правый', 'Правый'))

In [44]:
# Приведение к виду: 'SEDAN MECHANICAL 3.4', 'ROADSTER AUTOMATIC 1.5', ...
# col = 'vehicleConfiguration'
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('седан', 'SEDAN'))
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('внедорожник', 'ALLROAD'))
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('хэтчбек', 'HATCHBACK'))
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('хетчбэк', 'HATCHBACK'))
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('купе', 'COUPE'))
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('универсал', 'WAGON'))
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('минивэн', 'MINIVAN'))
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('пикап', 'PICKUP'))
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('кабриолет', 'CABRIO'))

# df_train[col] = df_train[col].apply(lambda x: str(x).replace('автомат', 'AUTOMATIC'))
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('вариатор', 'AUTOMATIC'))
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('механика', 'MECHANICAL'))
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('робот', 'ROBOT'))
# df_train[col] = df_train[col].apply(lambda x: str(x).replace(' other', ''))

In [24]:
# Замена "серебряный" -> "серебристый", "золотой" -> "золотистый"
# col = 'color'
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('серебряный', 'серебристый'))
# df_train[col] = df_train[col].apply(lambda x: str(x).replace('золотой', 'золотистый'))

In [15]:
# Замена "хетчбэк" -> "хэтчбек"
# df_train.bodyType = df_train.bodyType.apply(lambda x: str(x).replace('хетчбэк', 'хэтчбек'))

# Замена веществ. написание кол-ва дверей на целочисленное: 'седан 4.0 дв.' -> 'седан'
# df_train.bodyType = df_train.bodyType.apply(lambda x: str(x).replace('седан 4.0 дв.', 'седан'))

# Замена веществ. написание кол-ва дверей на целочисленное: 'седан 2.0 дв.' -> 'седан 2 дв.'
# df_train.bodyType = df_train.bodyType.apply(lambda x: str(x).replace('.0', ''))

In [91]:
df_train = pd.read_csv('data/avito_auto_train.csv')
df_train = df_train.dropna()
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42714 entries, 0 to 42722
Data columns (total 25 columns):
bodyType                42714 non-null object
brand                   42714 non-null object
color                   42714 non-null object
fuelType                42714 non-null object
modelDate               42714 non-null float64
name                    42714 non-null object
numberOfDoors           42714 non-null float64
productionDate          42714 non-null float64
vehicleConfiguration    42714 non-null object
vehicleTransmission     42714 non-null object
engineDisplacement      42714 non-null object
enginePower             42714 non-null object
description             42714 non-null object
mileage                 42714 non-null float64
Комплектация            42714 non-null object
Привод                  42714 non-null object
Руль                    42714 non-null object
Состояние               42714 non-null object
Владельцы               42714 non-null object
ПТС                     42714 non-null object
Таможня                 42714 non-null object
Владение                42714 non-null object
id                      42714 non-null int64
price                   42714 non-null float64
url                     42714 non-null object
dtypes: float64(5), int64(1), object(19)
memory usage: 8.5+ MB

In [17]:
# Дозаполнение пропущенных descr

# %%time
# idx_descr_na = df_train[df_train.description.isna()].index
# for idx in idx_descr_na:
#     df_train.loc[idx, 'description'] = process_tth_url(df_train.loc[idx]['url'], True)
# #     break

# df_train.description.isna().sum()

Wall time: 2h 36min 11s

105

In [42]:
# df_train['Владельцы'].unique()

array([2, 3, 0, 4, 1], dtype=int64)

In [44]:
# Замена числовых значений колонки на строковые
# df_train['Владельцы'] = df_train['Владельцы'].apply(\
#     lambda x: \
#         str(x)+' владельцев' if x==0 else\
#         str(x)+' владелец' if x==1 else\
#         str(x)+' владельца' if x==2 else '3 или более'
# )
# df_train['Владельцы'].unique()

array(['2 владельца', '3 или более', '0 владельцев', '1 владелец'],
      dtype=object)

In [76]:
df_train.to_csv('avito_auto_train.csv', index=False)

# df_train[df_train.description==-1].url
# df_train.loc[26].url

In [35]:
# !pip install ipywidgets

In [34]:
# jupiter nbextension enable --py widgetsnbextension

In [12]:
# 15.06.2020 - 2 ч.
# 16.06.2020 - 2 ч.
# 17.06.2020 - 2 ч.
# 18.06.2020 - 3 ч.
# 19.06.2020 - 1 ч.
# 20.06.2020 - 1 ч.
# 21.06.2020 - 1 ч.
# 22.06.2020 - 2 ч.
# 23.06.2020 - 1 ч.
# 24.06.2020 - 1 ч.
# 25.06.2020 - 2 ч.
# 29.06.2020 - 6 ч.