In [23]:
import pandas as pd
from bs4 import BeautifulSoup   
import requests

In [24]:
# Загрузка главной страницы сайта
url_main = 'https://auto.drom.ru/used/all/'
response_1 = requests.get(url_main) 
page_1 = BeautifulSoup(response_1.text, 'html.parser')

In [25]:
print(response_1)

<Response [200]>

In [26]:
# Цикл сбора ссылок на автомобили со страницы 
c = page_1.find_all('a' , class_="b-advItem")
cars_html = []
for i in range (len(c)):
    cars_html.append(c[i].attrs['href'].strip())

In [28]:
df = pd.DataFrame(columns = ['Name' , 'Двигатель', 'Мощность', 'Трансмиссия', 'Привод', 'Тип кузова', 'Цвет', 'Пробег, км', 'Руль' , 'Поколение' , 'Комплектация'])

In [29]:
df

Empty DataFrame
Columns: [Name, Двигатель, Мощность, Трансмиссия, Привод, Тип кузова, Цвет, Пробег, км, Руль, Поколение, Комплектация]
Index: []

In [37]:
n = 0
for link in cars_html:
    response = requests.get(link) 
    page = BeautifulSoup(response.text, 'html.parser')
    car = page.find_all('div' , class_ = 'b-media-cont_margin_b-size-xxs')
    d = {}
    d['Name'] = page.find('h1' , class_ = 'b-title b-title_type_h1 b-title_no-margin b-text-inline').text.strip()
    for i in range (len(car)):
        if i == 1 and car[i].find('span' , class_ = 'b-text-gray').text.replace(':' , '') == 'Мощность':
            d[car[i].find('span' , class_ = 'b-text-gray').text.replace(':' , '')] = car[i].find('div' , class_='b-link b-link_dashed').text.strip()
        else:
            d[car[i].find('span' , class_ = 'b-text-gray').text.replace(':' , '')] = car[i].find('span' , class_ = 'b-text-gray').next_element.next_element.strip()
    for item in d.items():
        df.loc[n , item[0]] = item[1]
    n += 1

In [38]:
df

,Name,Двигатель,Мощность,Трансмиссия,Привод,Тип кузова,Цвет,"Пробег, км",Руль,Поколение,Комплектация,Особые отметки
0,"Продажа Mercedes-Benz E-Class, 2006 год в Дубне","бензин, 3.5 л",272 л.с.,автомат,4WD,седан,серый,172000,левый,,,NaN
1,"Продажа Kia Rio, 2000 год в Бийске","бензин, 1.5 л",98 л.с.,автомат,передний,седан,серебристый,NaN,левый,NaN,NaN,NaN
2,"Продажа Лада 2107, 2005 год в Бийске","бензин, 1.6 л",76 л.с.,механика,задний,NaN,белый,52000,NaN,,,NaN
3,"Продажа BMW X5, 2018 год в Кемерово","дизель, 3.0 л",218 л.с.,автомат,4WD,NaN,серый,65000,левый,,,требуется ремонт или не на ходу
4,"Продажа Toyota Land Cruiser, 2002 год в Мирном","бензин, 4.7 л, ГБО",235 л.с.,автомат,4WD,джип/suv 5 дв.,серебристый,270000,левый,10 поколение,NaN,NaN
5,"Продажа Honda Grace, 2015 год в Находке","бензин, 1.5 л",132 л.с.,автомат,передний,NaN,NaN,"55000, б/п по РФ",правый,,,NaN
6,"Продажа Cadillac DeVille, 1984 год в Уссурийске",бензин,NaN,автомат,NaN,NaN,белый,50000,NaN,NaN,NaN,NaN
7,"Продажа Mercedes-Benz C-Class, 2005 год в Ново...","бензин, 1.8 л",143 л.с.,автомат,задний,купе,красный,180000,левый,,,NaN
8,"Продажа Лада 2114 Самара, 2011 год в Омске","бензин, 1.6 л",81 л.с.,механика,передний,хэтчбек 5 дв.,белый,NaN,левый,,NaN,NaN
9,"Продажа Nissan Note, 2014 год в Саяногорске","бензин, 1.2 л",79 л.с.,автомат,передний,NaN,серый,NaN,правый,,NaN,NaN
10,"Продажа Kia Sorento, 2013 год в Салехарде","дизель, 2.2 л",197 л.с.,автомат,4WD,NaN,коричневый,78000,левый,,NaN,NaN
11,"Продажа Hyundai i30, 2012 год в Омске","бензин, 1.6 л",130 л.с.,автомат,передний,хэтчбек 5 дв.,серый,101000,левый,,,NaN
12,"Продажа Лада 2108, 1987 год в Севастополе","бензин, 1.3 л",64 л.с.,механика,передний,хэтчбек 3 дв.,бордовый,44000,левый,,,NaN
13,"Продажа Nissan Note, 2008 год в Северобайкальске","бензин, 1.5 л",109 л.с.,автомат,передний,NaN,NaN,NaN,правый,,NaN,NaN
14,"Продажа Kia Rio, 2015 год в Сургуте","бензин, 1.4 л",107 л.с.,механика,передний,седан,серебристый,89000,левый,,,NaN
15,"Продажа Toyota Camry, 1991 год в Уссурийске","бензин, 2.0 л",140 л.с.,автомат,передний,седан,белый,NaN,правый,,NaN,NaN
16,"Продажа Volkswagen Golf, 2004 год в Новочеркасске","бензин, 1.4 л, ГБО",75 л.с.,механика,передний,хэтчбек 5 дв.,черный,196000,левый,NaN,NaN,NaN
17,"Продажа Mazda Capella, 1999 год в Иркутске","бензин, 2.0 л",140 л.с.,автомат,передний,универсал,серебристый,350000,правый,,NaN,NaN
18,"Продажа Kia Sorento, 2012 год в Красноярске","бензин, 2.4 л",175 л.с.,механика,4WD,NaN,NaN,NaN,левый,,NaN,NaN
19,"Продажа Лада 2107, 2006 год в Омске","бензин, 1.6 л, ГБО",76 л.с.,механика,задний,NaN,белый,NaN,NaN,,,NaN